import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Navbar from "../../components/navbar/Navbar";
import getCurrentUser from "./actions/getCurrentUser";
import {ReduxProvider} from "@/redux/provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar currentUser={currentUser} />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
